### ISSUE TITLE
BCD ispis rezultata

### ISSUE THREAD

**Issue by GojakMilica** [pfe-rs/lk-s-2022-estimacija-pokreta#5]
BCD treba da izbaci posle svake iteracije sledeće rezultate:
- `.npy` fajlove sa flow field
- `.npy` fajlove sa dodatnim podacima koji se dele između iteracija

**Comment by NovakTJ** [comment]
taj fajl se zove "gotova slika" pa neki parametri - nije zapravo slika nego gotova matrica flow vektora koja se moze vizuelizovati
